service: ephibot
runtime: go
api_version: go1

inbound_services:
  - warmup


handlers:

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /static
  static_dir: static/

- url: /.*
  script: _go_app
  secure: always


